# Site settings
title: Blocs.fr
description: Directeur technique et ingénieur logiciel en freelance
image: /assets/img/prof_moi_500.png
author: Jonathan Serra
permalink: /:categories/:title

# User settings
username: Blocs
user_description: Directeur technique et ingénieur logiciel freelance
user_title: Ingénieur logiciel
email: jonathan@blocs.fr
twitter_username: cryptoblocs
github_username: Slals

collections:
  posts:
    output: true
    permalink: /articles/:title
  projects:
    output: true
    permalink: /projects/:title

twitter:
  username: cryptoblocs
  card: summary_large_image

logo: /assets/img/logo.png

lang: fr-FR

# Google-analytics
google-analytics:
  id: ""

sass:
  sass_dir: src/styles
  style: compact

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

highlighter: rouge
