# Site settings
title: Blocs
description: Développeur disponible en freelance
image: /assets/img/prof_moi_500.png
author: Jonathan Serra
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jonathan Serra
user_description: Développeur disponible en freelance
user_title: Ingénieur logiciel
email: jonathan@cryptoblocs.fr
twitter_username: cryptoblocs
github_username:  Slaals

twitter:
  username: cryptoblocs
  card: summary

logo: /assets/img/prof_moi_500.png

lang: fr-FR

# Google-analytics
google-analytics:
  id: ""

sass:
  sass_dir: src/styles

plugins:
  - jekyll-seo-tag
