# Site settings
title: Blocs.fr
description: Développeur Freelance Golang Docker React Blockchain. Parfait match pour un CTO (directeur technique) pour encadrer votre projet.
image: /assets/img/prof_moi_500.png
author: Jonathan Serra
permalink: /:categories/:title

# User settings
username: Blocs
user_description: Développeur Freelance Golang Docker React Blockchain. Parfait match pour un CTO (directeur technique) pour encadrer votre projet.
user_title: Développeur Freelance
email: jonathan@blocs.fr
twitter_username: cryptoblocs
github_username: Slals

collections:
  posts:
    output: true
    permalink: /articles/:title
  projects:
    output: true
    permalink: /projects/:title

twitter:
  username: _blocs
  card: summary_large_image

logo: /assets/img/logo.png

lang: fr-FR

# Google-analytics
google-analytics:
  id: ""

sass:
  sass_dir: src/styles
  style: compact

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

highlighter: rouge
